version: "3"

services:
  app:
    container_name: app-sigma
    image: node:16
    tty: true
    volumes:
      - "../..:/home/app"
    environment:
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      NGROK_TOKEN: "${NGROK_TOKEN}"
      DATABASE_URL: "postgresql://postgres:mypassword@db"
    depends_on:
      - db
  db:
    container_name: db-sigma
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: "mypassword"
  