-- Generate with https://mockaroo.com/

insert into "sigma"."person" ( full_name, email, city, department) values ( 'Helge', 'hlorain0@hibu.com', 'Lebowakgomo', 'Vaulx-en-Velin');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Dukey', 'dmilton1@joomla.org', 'Tānk', 'Kangān');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Dillon', 'dgeleman2@elpais.com', 'Wanshi', 'Qiulu');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Ermentrude', 'egomer3@pagesperso-orange.fr', 'Battung', 'Varberg');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Vicki', 'vbuney4@nyu.edu', 'Cimalati', 'Awilega');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Modestia', 'mdur5@t.co', 'Jiangkou', 'Fuyo');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Gnni', 'gtiler6@mail.ru', 'Baicheng', 'Jianyi');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Pearce', 'pmantram7@barnesandnoble.com', 'Amadeo', 'Ryazan’');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Cecil', 'cbletsoe8@photobucket.com', 'Lianozovo', 'Parajara');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Hilary', 'hchristofle9@bbc.co.uk', 'Dalongzhan', 'Río Gallegos');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Robinette', 'rmcivora@wordpress.org', 'Tianjiazhuang', 'Yegor’yevsk');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Reinold', 'rebbuttb@flavors.me', 'Riba de Ave', 'Freixo de Numão');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Tiffany', 'toutridgec@ted.com', 'Södra Sandby', 'Thị Trấn Kim Tân');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Tobey', 'tciccid@jiathis.com', 'Yiliu', 'Turbo');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Verge', 'vyesinove@youtu.be', 'Giado', 'Ersekë');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Glori', 'gcostyf@hibu.com', 'La Valette-du-Var', 'Paris 15');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Shir', 'smathewsong@about.com', 'Marseille', 'Ndeaboh');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Lezlie', 'lcheerh@trellian.com', 'Thika', 'Sävedalen');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Cloe', 'cyurkini@domainmarket.com', 'Ceper', 'Zharrëz');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Gilberto', 'gcallerj@fema.gov', 'Rauna', 'Shimen');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Erna', 'ealdisk@imageshack.us', 'Guang’an', 'Saint-Pierre');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Moshe', 'mtattersilll@whitehouse.gov', 'Veliki Preslav', 'Songculan');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Boothe', 'besherwoodm@earthlink.net', 'Pilcaniyeu', 'Izborsk');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Hally', 'hgarrityn@hatena.ne.jp', 'Ciparay', 'Denpasar');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Sal', 'slenchenkoo@illinois.edu', 'Janaka', 'Poitiers');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Tam', 'tdorowp@homestead.com', 'Mpumalanga', 'Youchou');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Keely', 'kauselloq@omniture.com', 'Mat-i', 'Pinhal de Frades');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Winona', 'wosgordbyr@army.mil', 'Shicha', 'Santo Tomás');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Ludovika', 'lbainbrigges@themeforest.net', 'Emiliano Zapata', 'Bergen');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Deanne', 'djosephovt@cloudflare.com', 'Rancamaya', 'Balgatay');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Humberto', 'hrasmusu@homestead.com', 'Xingdian', 'Višnjevac');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Hall', 'hwynev@domainmarket.com', 'Charleston', 'Dukhovnitskoye');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Callean', 'cduckerw@cnn.com', 'Krajan Kerjo', 'Las Vegas');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Pauly', 'pfautlyx@census.gov', 'Limbuš', 'Xiaoguai');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Lindi', 'lmacmeanmay@google.de', 'Wiesbaden', 'Yangdenghu');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Aurie', 'acostiganz@wufoo.com', 'Runaway Bay', 'Vladimirskaya');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Tiffany', 'tantusch10@meetup.com', 'Čair', 'Hostos');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Bent', 'btant11@sourceforge.net', 'Tashang', 'Sundbyberg');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Gwendolyn', 'gtenbrug12@baidu.com', 'Suvorovskaya', 'Emiliano Zapata');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Violet', 'vlegh13@posterous.com', 'Coroatá', 'Adar');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Merrill', 'mtop14@xrea.com', 'Moholm', 'Staromyshastovskaya');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Jesse', 'jsymcock15@indiegogo.com', 'Dunhao', 'Gävle');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Salim', 'sfeaver16@oaic.gov.au', 'Atar', 'Catamayo');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Sharlene', 'smahomet17@yahoo.com', 'Pljevlja', 'Rychwał');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Gaven', 'gtrigg18@businessweek.com', 'Utara', 'Znojmo');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Kiley', 'kivanaev19@amazonaws.com', 'Manzanillo', 'Landi Kotal');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Wilone', 'wpady1a@ibm.com', 'Fraga', 'Kaniv');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Tobey', 'tcorrea1b@tinypic.com', 'Bolnisi', 'Tibigan');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Zoe', 'zcollop1c@webeden.co.uk', 'Selydove', 'Pajeksan');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Felicio', 'fbramwich1d@who.int', 'Zuogaimanma', 'Luzern');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Almeda', 'aketteman1e@hp.com', 'An Nāşirīyah', 'Angoulême');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Teirtza', 'tgirardi1f@webmd.com', 'Hongtang', 'Pingshanhu');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Cornelle', 'csager1g@state.gov', 'Emmen', 'Montes Claros');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Tara', 'tfochs1h@google.fr', 'Kastav', 'Roczyny');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Chery', 'cwebley1i@themeforest.net', 'Sandia', '‘Aqrah');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Dwain', 'dpigram1j@addthis.com', 'Taipinghu', 'Hengjie');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Bent', 'bcordell1k@theglobeandmail.com', 'Khilok', 'Liwonde');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Chelsie', 'ccowe1l@github.com', 'Río Sereno', 'Aston');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Alf', 'ascrowston1m@vk.com', 'Iporá', 'Krajan Dua Putukrejo');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Loralyn', 'lsymon1n@infoseek.co.jp', 'Tân Hưng', 'Qarqania');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Aurelie', 'amacpharlain1o@vk.com', 'Camabatela', 'Tallinn');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Robinetta', 'rswetman1p@lycos.com', 'Krasyliv', 'Budayuan');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Vere', 'vpattie1q@indiegogo.com', 'Karpushikha', 'Río Tercero');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Darya', 'dphippin1r@unicef.org', 'Nanshan', 'Katsuura');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Mar', 'mbock1s@nationalgeographic.com', 'Vitória de Santo Antão', 'Chropyně');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Meade', 'mbage1t@alibaba.com', 'Krahës', 'Qorashina');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Lurline', 'lcordel1u@photobucket.com', 'Otaniemi', 'Shangsanji');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Rhiamon', 'rworsfield1v@fema.gov', 'Krajan Satu', 'Norrköping');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Dimitry', 'dandino1w@nasa.gov', 'Xinchenglu', 'Lekaj');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Atalanta', 'amuff1x@amazon.co.jp', 'Xinzhai', 'Gwangju');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Nissy', 'nhuxley1y@yellowbook.com', 'Maisí', 'Kelburn');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Lissie', 'lspoole1z@ucla.edu', 'Tabug', 'Mzuzu');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Ann', 'amcginly20@mozilla.com', 'Chexi', 'Yaita');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Gamaliel', 'gswancott21@pcworld.com', 'Omurtag', 'Ustupo');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Quintana', 'qcurner22@redcross.org', 'Silva Jardim', 'Viradouro');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Abelard', 'agarton23@thetimes.co.uk', 'Vallauris', 'Isesaki');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Fara', 'fpaice24@posterous.com', 'Pubal', 'Kiel');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Cesaro', 'cnorthill25@com.com', 'Sokal’', 'Paty do Alferes');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Ingrid', 'ideeth26@nyu.edu', 'Cầu Giát', 'Dabao’anzhen');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Gayler', 'gweeds27@123-reg.co.uk', 'Polel Diaoubé', 'Bultfontein');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Carolee', 'cbon28@microsoft.com', 'Paoay', 'Pompéia');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Wadsworth', 'wdannehl29@si.edu', 'Blangpulo', 'Ambarawa');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Jennilee', 'jpaladini2a@creativecommons.org', 'Rantaupanjang', 'Ganja');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Rosemarie', 'rfebry2b@seesaa.net', 'Alupay', 'Avellaneda');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Brier', 'bperri2c@latimes.com', 'Anbyŏn-ŭp', 'Tân Việt');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Betsey', 'bwhitehouse2d@mtv.com', 'San Andrés', 'Gingsir');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Antony', 'azemler2e@ycombinator.com', 'Shuangjie', 'Micheng');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Guntar', 'garmit2f@oakley.com', 'Lyublino', 'Hollola');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Gael', 'gwatford2g@webnode.com', 'Brokopondo', 'Campo Viera');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Britteny', 'bnobriga2h@dailymail.co.uk', 'Nowy Staw', 'Nanzamu');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Giulia', 'gaxby2i@senate.gov', 'Piancheng', 'Kawaliwu');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Glenden', 'gseatter2j@dot.gov', 'Shuyuan', 'Mandiana');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Angelique', 'acousen2k@creativecommons.org', 'Ospina', 'Unidos');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Fernandina', 'fsansam2l@cbsnews.com', 'Söderköping', 'Toutai');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Kati', 'kferie2m@infoseek.co.jp', 'Shupenzë', 'Corujeira');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Sayers', 'sgwatkin2n@bloglovin.com', 'Níkaia', 'Dobropillya');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Bonita', 'bdangelo2o@census.gov', 'Gisiliba', 'Lilio');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Lothario', 'lgonoude2p@nba.com', 'Jovim', 'Zhangting');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Lennie', 'lleake2q@google.ru', 'Połaniec', 'Diawara');
insert into "sigma"."person" ( full_name, email, city, department) values ( 'Robbi', 'rheers2r@epa.gov', 'Ciranca Satu', 'Tulay na Lupa');
