export const opp:any = {
  oppHits: [
    {
      id: "329382",
      number: "NNH20ZDA001N-EPRV",
      title: "ROSES 2020: Extreme Precision Radial Velocity Foundation Science",
      agencyCode: "NASA-HQ",
      agency: "NASA Headquarters",
      openDate: "10/09/2020",
      closeDate: "12/17/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["43.001"],
    },
    {
      id: "328459",
      number: "HRSA-21-034",
      title:
        "Maternal and Child Health (MCH) Leadership, Education, and Advancement in Undergraduate Pathways (LEAP) Training Program",
      agencyCode: "HHS-HRSA",
      agency: "Health Resources and Services Administration",
      openDate: "10/09/2020",
      closeDate: "01/07/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["93.110"],
    },
    {
      id: "329381",
      number: "DE-FOA-0002372",
      title:
        "Request for Information on Office of Energy Efficiency &amp; Renewable Energy&rsquo;s Medium- and Heavy-Duty Truck Research and Development Activities &amp; SuperTruck Initiative",
      agencyCode: "DOE-NETL",
      agency: "National Energy Technology Laboratory",
      openDate: "10/09/2020",
      closeDate: "11/09/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["81.086"],
    },
    {
      id: "329365",
      number: "21-512",
      title: "Cybersecurity Innovation for Cyberinfrastructure",
      agencyCode: "NSF",
      agency: "National Science Foundation",
      openDate: "10/09/2020",
      closeDate: "01/08/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["47.070"],
    },
    {
      id: "329366",
      number: "19-551",
      title: "GROWING CONVERGENCE RESEARCH",
      agencyCode: "NSF",
      agency: "National Science Foundation",
      openDate: "10/09/2020",
      closeDate: "02/01/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: [
        "47.076",
        "47.049",
        "47.070",
        "47.041",
        "47.075",
        "47.074",
        "47.083",
        "47.079",
        "47.050",
      ],
    },
    {
      id: "329361",
      number: "72065620APS00002",
      title:
        "Supporting Greater Socio-Economic Development and Recovery in Cabo Delgado APS",
      agencyCode: "USAID-MOZ",
      agency: "Mozambique USAID-Maputo",
      openDate: "10/09/2020",
      closeDate: "12/15/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["98.001"],
    },
    {
      id: "329383",
      number: "EPA-G2021-STAR-G1",
      title:
        "Interventions and Communication Strategies to Reduce Health Risks of Wildland Fire Smoke Exposures",
      agencyCode: "EPA",
      agency: "Environmental Protection Agency",
      openDate: "10/09/2020",
      closeDate: "12/15/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["66.509"],
    },
    {
      id: "329384",
      number: "EPA-G2021-STAR-G2",
      title:
        "Early Career: Interventions and Communication Strategies to Reduce Health Risks of Wildland Fire Smoke Exposures",
      agencyCode: "EPA",
      agency: "Environmental Protection Agency",
      openDate: "10/09/2020",
      closeDate: "12/15/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["66.509"],
    },
    {
      id: "329386",
      number: "HHS-2021-ACF-OCS-ET-1959",
      title:
        "Community Services Block Grant (CSBG) CARES Act Rapid-Cycle Impact Projects",
      agencyCode: "HHS-ACF-OCS",
      agency: "Administration for Children and Families - OCS",
      openDate: "10/09/2020",
      closeDate: "",
      oppStatus: "forecasted",
      docType: "forecast",
      cfdaList: ["93.569"],
    },
    {
      id: "329362",
      number: "N00014-21-S-B001",
      title:
        "FY2021 Long Range Broad Agency Announcement (BAA) for Navy and Marine Corps Science and Technology",
      agencyCode: "DOD-ONR",
      agency: "Office of Naval Research",
      openDate: "10/08/2020",
      closeDate: "09/30/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["12.300"],
    },
    {
      id: "329360",
      number: "INL21CA0002-COSTARICA-GBVCITIZENSECURITY",
      title:
        "Response to Gender Based Violence Technical Assistance for Shelters",
      agencyCode: "DOS-INL",
      agency: "Bureau of International Narcotics-Law Enforcement",
      openDate: "10/08/2020",
      closeDate: "12/08/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["19.704"],
    },
    {
      id: "329375",
      number: "PAR-20-307",
      title:
        "Developmental AIDS Research Center on Mental Health and HIV/AIDS (P30 Clinical Trial Optional)",
      agencyCode: "HHS-NIH11",
      agency: "National Institutes of Health",
      openDate: "10/08/2020",
      closeDate: "09/13/2023",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["93.242"],
    },
    {
      id: "329377",
      number: "PAR-20-308",
      title:
        "AIDS Research Center on Mental Health and HIV/AIDS (P30 Clinical Trial Optional)",
      agencyCode: "HHS-NIH11",
      agency: "National Institutes of Health",
      openDate: "10/08/2020",
      closeDate: "09/13/2023",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["93.242"],
    },
    {
      id: "329378",
      number: "PAR-20-306",
      title:
        "National Dental Practice-Based Research Network Clinical Trial or Observational Study Planning and Implementation Cooperative Agreement (UG3/UH3 Clinical Trial Optional)",
      agencyCode: "HHS-NIH11",
      agency: "National Institutes of Health",
      openDate: "10/08/2020",
      closeDate: "09/07/2023",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["93.121"],
    },
    {
      id: "329363",
      number: "PAR-21-030",
      title:
        "Late-Stage Translation of Biomedical and Behavioral Research Results in Arthritis and Musculoskeletal and Skin Diseases from Academic/Non-profit Lab to Marketplace (SBIR [R43/R44] Clinical Trial Not Allowed)",
      agencyCode: "HHS-NIH11",
      agency: "National Institutes of Health",
      openDate: "10/08/2020",
      closeDate: "09/05/2022",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["93.846"],
    },
    {
      id: "329355",
      number: "21-511",
      title:
        "Accelerating Research through International Network-to-Network Collaborations",
      agencyCode: "NSF",
      agency: "National Science Foundation",
      openDate: "10/08/2020",
      closeDate: "01/04/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: [
        "47.079",
        "47.070",
        "47.074",
        "47.075",
        "47.049",
        "47.083",
        "47.076",
        "47.041",
        "47.050",
      ],
    },
    {
      id: "329358",
      number: "CDC-RFA-GH21-2164",
      title:
        "Shoulder to Shoulder: Accompanying Ministries of Health in Central America in Strengthening Local and Global Health Security",
      agencyCode: "HHS-CDC-CGH",
      agency: "Centers for Disease Control - CGH",
      openDate: "10/08/2020",
      closeDate: "",
      oppStatus: "forecasted",
      docType: "forecast",
      cfdaList: ["93.318"],
    },
    {
      id: "329359",
      number: "RFA-CE-21-002",
      title:
        "Research Grants to Develop or Identify Effective Strategies to Prevent Overdose Involving Illicit Stimulants and Polysubstance Use Involving Stimulants",
      agencyCode: "HHS-CDC-HHSCDCERA",
      agency: "Centers for Disease Control and Prevention - ERA",
      openDate: "10/08/2020",
      closeDate: "",
      oppStatus: "forecasted",
      docType: "forecast",
      cfdaList: ["93.136"],
    },
    {
      id: "329357",
      number: "2021NEA03LFTP",
      title: "NEA Literature Fellowships: Translation Projects, FY2022",
      agencyCode: "NEA",
      agency: "National Endowment for the Arts",
      openDate: "10/08/2020",
      closeDate: "01/13/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["45.024"],
    },
    {
      id: "329331",
      number: "72049721RFI00001",
      title:
        "Request for Information (RFI) and Sources Sought: New Marine and Fisheries Program",
      agencyCode: "USAID-IND",
      agency: "Indonesia USAID-Jakarta",
      openDate: "10/08/2020",
      closeDate: "",
      oppStatus: "forecasted",
      docType: "forecast",
      cfdaList: ["98.001"],
    },
    {
      id: "329368",
      number: "RFA-AI-20-056",
      title:
        "Coccidioidomycosis Collaborative Research Centers (U19 Clinical Trial Not Allowed)",
      agencyCode: "HHS-NIH11",
      agency: "National Institutes of Health",
      openDate: "10/08/2020",
      closeDate: "02/18/2021",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["93.855"],
    },
    {
      id: "329364",
      number: "DE-FOA-0002428",
      title:
        "Notice of Intent to issue DE-FOA-0002397 titled University Turbine Systems Research (UTSR) &ndash; Focus on Hydrogen Fuels",
      agencyCode: "DOE-NETL",
      agency: "National Energy Technology Laboratory",
      openDate: "10/08/2020",
      closeDate: "12/15/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["81.089"],
    },
    {
      id: "329288",
      number: "SWMFY2021",
      title: "Solid Waste Management Grant Program",
      agencyCode: "USDA-RUS",
      agency: "Utilities Programs",
      openDate: "10/07/2020",
      closeDate: "12/31/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["10.762"],
    },
    {
      id: "329350",
      number: "TATFY21",
      title: "Technical Assistance and Training Grant Program",
      agencyCode: "USDA-RUS",
      agency: "Utilities Programs",
      openDate: "10/07/2020",
      closeDate: "12/31/2020",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["10.761"],
    },
    {
      id: "329329",
      number: "21-508",
      title:
        "Transitions to Excellence in Molecular and Cellular Biosciences Research",
      agencyCode: "NSF",
      agency: "National Science Foundation",
      openDate: "10/07/2020",
      closeDate: "",
      oppStatus: "posted",
      docType: "synopsis",
      cfdaList: ["47.074"],
    },
  ],
};

export default opp;
