name: Build and publish docker agape develop image
on:
  push:
    branches:
      - agape@develop
    paths:
      - 'agape/**'
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        name: Checks-out your repository

      # https://github.com/marketplace/actions/docker-login
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # I just want to keep the latest version for demos 
      - working-directory: agape
        run: |
          docker build . -t mapineda48/agape-dev
          docker push mapineda48/agape-dev