name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
    paths:
      - 'social/**'
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@mapineda48'
          
      - working-directory: social
        run: |
          yarn install
          yarn build
          cd dist && npm publish

        env:
          NODE_ENV: production
          CI: false
          # CRA config
          INLINE_RUNTIME_CHUNK: false
          GENERATE_SOURCEMAP: false
          # github access
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}